hl.on("hyprland.start", function()
    hl.exec_cmd("hyprlock")
    hl.exec_cmd("systemctl --user start --ignore-dependencies xdg-desktop-portal")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("[workspace 10 silent] v2rayN")
    hl.exec_cmd("quickshell")
    -- hl.exec_cmd("python ~/.c/code/scripts/randomWallpaper.py")
    hl.exec_cmd("fcitx5")
end)