hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("waypaper --restore")
    hl.exec_cmd("[workspace 10 silent] v2rayN")
    hl.exec_cmd("quickshell")
    hl.exec_cmd("python ~/.c/code/scripts/randomWallpaper.py")
    hl.exec_cmd("fcitx5")
end)