confirm_os_window_close 0
font_family Noto Sans CJK SC

map ctrl+backspace send_text all \x17

include ~/.cache/wal/colors-kitty.conf
background_opacity 0.3

dynamic_background_opacity yes
font_size 12


